// Categories: action, adventure, emulator, io, other, platformer, puzzle, racing, roblox, sports, strategy
const games = [
    {name:"1 On 1 Soccer", url:"./games/1on1-soccer/", category:"sports"},
    {name:"1v1.lol", url:"./games/1v1lol/", category:"action"},
    {name:"10 Bullets", url:"./games/10-bullets/", category:"strategy"},
    {name:"10 Minutes Till Dawn", url:"./games/10-minutes-till-dawn/", category:"action"},
    {name:"2048", url:"./games/2048/", category:"puzzle"},
    {name:"A Dance of Fire and Ice", url:"./games/a-dance-of-fire-and-ice/", category:"platformer"},
    {name:"Age of War 2", url:"./games/age-of-war-2/", category:"strategy"},
    {name:"Among Us", url:"./games/among-us/", category:"adventure"},
    {name:"Angry Birds", url:"./games/angry-birds/", category:"action"},
    {name:"Appel", url:"./games/appel/", category:"platformer"},
    {name:"Awesome Tanks 2", url:"./games/awesome-tanks-2/", category:"action"},
    {name:"Bad Ice Cream 3", url:"./games/bad-ice-cream-3/", category:"platformer"},
    {name:"Bad Piggies", url:"./games/bad-piggies/", category:"action"},
    {name:"Bad Time Simulator", url:"./games/bad-time-simulator/", category:"action"},
    {name:"Baldi's Basics", url:"./games/baldis-basics/", category:"other"},
    {name:"Basket Random", url:"./games/basket-random/", category:"sports"},
    {name:"Basketball Stars", url:"./games/basketball-stars/", category:"sports"},
    {name:"Big Flappy Tower Tiny Square", url:"./games/big-flappy-tower-tiny-square/", category:"platformer"},
    {name:"Big Ice Tower Tiny Square", url:"./games/big-ice-tower-tiny-square/", category:"platformer"},
    {name:"Big Neon Tower Tiny Square", url:"./games/big-neon-tower-tiny-square/", category:"platformer"},
    {name:"Big Tower Tiny Square", url:"./games/big-tower-tiny-square/", category:"platformer"},
    {name:"Big Tower Tiny Square 2", url:"./games/big-tower-tiny-square-2/", category:"platformer"},
    {name:"Bit Planes", url:"./games/bit-planes/", category:"action"},
    {name:"BitLife", url:"./games/bitlife/", category:"other"},
    {name:"Block Blast", url:"./games/block-blast/", category:"puzzle"},
    {name:"Bloons Tower Defense 5", url:"./games/bloons-tower-defense-5/", category:"strategy"},
    {name:"Bob The Robber 5", url:"./games/bob-the-robber-5", category:"adventure"},
    {name:"Boxing Random", url:"./games/boxing-random/", category:"sports"},
    {name:"Brawl Stars", url:"./games/brawl-stars", category:"action"},
    {name:"Candy Crush", url:"./games/candy-crush", category:"puzzle"},
    {name:"Celeste", url:"./games/celeste/", category:"platformer"},
    {name:"Chop Trees Obby", url:"./games/chop-trees-obby/", category:"roblox"},
    {name:"Cookie Clicker", url:"./games/cookie-click/", category:"other"},
    {name:"Crossy Road", url:"./games/crossy-road/", category:"adventure"},
    {name:"Cut the Rope", url:"./games/cut-the-rope/", category:"puzzle"},
    {name:"Cut the Rope: Holiday Gift", url:"./games/cut-the-rope-holiday-gift/", category:"puzzle"},
    {name:"Dadish 3", url:"./games/dadish-3/", category:"platformer"},
    {name:"Death Run 3D", url:"./games/death-run-3d/", category:"action"},
    {name:"Doodle Jump", url:"./games/doodle-jump/", category:"platformer"},
    {name:"Doomz.io", url:"./games/doomzio/", category:"io"},
    {name:"Drift Boss", url:"./games/drift-boss/", category:"racing"},
    {name:"Drive Mad (Fanmade)", url:"./games/drive-mad/", category:"racing"},
    {name:"Duck Life 5", url:"./games/duck-life-5/", category:"adventure"},
    {name:"Duck Life Space", url:"./games/duck-life-space/", category:"adventure"},
    {name:"Eaglercraft", url:"./games/eaglercraft/", category:"other"},
    {name:"Escape Road", url:"./games/escape-road/", category:"action"},
    {name:"Escape Road 2", url:"./games/escape-road-2/", category:"action"},
    {name:"Fancy Pants Adventures", url:"./games/fancy-pants-adventures/", category:"platformer"},
    {name:"Fireboy and Watergirl 3", url:"./games/fireboy-and-watergirl-3/", category:"platformer"},
    {name:"Five Nights at Freddy's 4", url:"./games/five-nights-at-freddys-4/", category:"action"},
    {name:"Fly the Farthest", url:"./games/fly-the-farthest/", category:"roblox"},
    {name:"Fruit Ninja", url:"./games/fruit-ninja/", category:"action"},
    {name:"Geometry Dash (Scratch)", url:"./games/geometry-dash/", category:"action"},
    {name:"Geometry Dash Lite", url:"./games/geometry-dash-lite/", category:"action"},
    {name:"Geometry Dash Meltdown (Scratch)", url:"./games/geometry-dash-meltdown/", category:"action"},
    {name:"Geometry Dash Subzero (Scratch)", url:"./games/geometry-dash-subzero/", category:"action"},
    {name:"Geometry Dash World (Scratch)", url:"./games/geometry-dash-world/", category:"action"},
    {name:"Getting Over It (Scratch)", url:"./games/getting-over-it/", category:"platformer"},
    {name:"Gun Knight", url:"./games/gun-knight/", category:"action"},
    {name:"Gun Mayhem", url:"./games/gun-mayhem/", category:"action"},
    {name:"Hei$t", url:"./games/heist/", category:"adventure"},
    {name:"Helix Jump", url:"./games/helix-jump/", category:"other"},
    {name:"Henry Stickmin: Escaping the Prison", url:"./games/henry-stickmin-escaping-the-prison/", category:"adventure"},
    {name:"Hole.io", url:"./games/holeio/", category:"io"},
    {name:"Hollow Knight", url:"./games/hollow-knight/", category:"platformer"},
    {name:"Icy Purple Head", url:"./games/icy-purple-head/", category:"adventure"},
    {name:"Idle Breakout", url:"./games/idle-breakout/", category:"action"},
    {name:"Idle Miner Tycoon", url:"./games/idle-miner-tycoon/", category:"other"},
    {name:"Infinite Craft", url:"./games/infinite-craft/", category:"other"},
    {name:"Jailbreak Obby", url:"./games/jailbreak-obby/", category:"roblox"},
    {name:"Justfall.lol", url:"./games/justfalllol/", category:"action"},
    {name:"Kingdom Rush", url:"./games/kingdom-rush/", category:"strategy"},
    {name:"Kingdom Rush: Frontiers", url:"./games/kingdom-rush-frontiers/", category:"strategy"},
    {name:"Knights Battle Arena", url:"./games/knights-battle-arena/", category:"action"},
    {name:"Layers Roll", url:"./games/layers-roll/", category:"other"},
    {name:"Learn to Fly 3", url:"./games/learn-to-fly-3/", category:"adventure"},
    {name:"Little Alchemy 2", url:"./games/little-alchemy-2/", category:"other"},
    {name:"Melon Playground", url:"./games/melon-playground/", category:"other"},
    {name:"Merge Round Racers", url:"./games/merge-round-racers/", category:"racing"},
    {name:"Monkey Mart", url:"./games/monkey-mart/", category:"adventure"},
    {name:"Moto X 3M I", url:"./games/motox3m-1/", category:"racing"},
    {name:"Moto X 3M II", url:"./games/motox3m-2/", category:"racing"},
    {name:"Moto X 3M III", url:"./games/motox3m-3/", category:"racing"},
    {name:"Moto X 3M - Pool Party", url:"./games/motox3m-poolparty/", category:"racing"},
    {name:"Moto X 3M - Spooky Land", url:"./games/motox3m-spookyland/", category:"racing"},
    {name:"Moto X 3M - Winter Land", url:"./games/motox3m-winterland/", category:"racing"},
    {name:"N-Gon", url:"./games/ngon/", category:"platformer"},
    {name:"Only Up", url:"./games/only-up/", category:"platformer"},
    {name:"OvO Dimensions", url:"./games/ovo-dimensions/", category:"platformer"},
    {name:"Paper.io 2", url:"./games/paperio-2/", category:"io"},
    {name:"Pixel Shooter", url:"./games/pixel-shooter/", category:"action"},
    {name:"Parking Fury 3", url:"./games/parking-fury-3/", category:"puzzle"},
    {name:"Plants vs Zombies", url:"./games/plants-vs-zombies/", category:"action"},
    {name:"PolyTrack", url:"./games/polytrack/", category:"racing"},
    {name:"Quantum Clicker", url:"./games/quantum-clicker/", category:"other"},
    {name:"Raft Wars 2", url:"./games/raft-wars-2/", category:"adventure"},
    {name:"Rainbow Obby", url:"./games/rainbow-obby/", category:"roblox"},
    {name:"Retro Bowl", url:"./games/retrobowl/", category:"sports"},
    {name:"Retro Bowl College", url:"./games/retrobowl-college/", category:"sports"},
    {name:"RocketGoal.io", url:"./games/rocketgoalio/", category:"io"},
    {name:"Rolling Sky", url:"./games/rolling-sky/", category:"other"},
    {name:"Rooftop Snipers", url:"./games/rooftop-snipers/", category:"action"},
    {name:"Run 3", url:"./games/run3/", category:"platformer"},
    {name:"Save My Pet", url:"./games/save-my-pet/", category:"strategy"},
    {name:"Slope", url:"./games/slope/", category:"platformer"},
    {name:"Slope Multiplayer", url:"./games/slope-multiplayer/", category:"platformer"},
    {name:"Snake.io", url:"./games/snakeio/", category:"io"},
    {name:"Snow Rider 3D", url:"./games/snow-rider-3d/", category:"racing"},
    {name:"Snowball.io", url:"./games/snowballio/", category:"io"},
    {name:"Soccer Random", url:"./games/soccer-random/", category:"sports"},
    {name:"Speed Per Click", url:"./games/speed-per-click/", category:"roblox"},
    {name:"Spiral Roll", url:"./games/spiral-roll/", category:"other"},
    {name:"Steal A Brainrot", url:"./games/steal-a-brainrot/", category:"roblox"},
    {name:"Stick War II", url:"./games/stick-war-2/", category:"strategy"},
    {name:"Stick Warriors", url:"./games/stick-warriors/", category:"action"},
    {name:"Stickman Climb", url:"./games/stickman-climb/", category:"platformer"},
    {name:"Stickman Hook", url:"./games/stickman-hook/", category:"platformer"},
    {name:"Stick Ninja Academy", url:"./games/sticky-ninja-academy", category:"action"},
    {name:"Stumble Guys", url:"./games/stumble-guys/", category:"platformer"},
    {name:"Subway Surfers: San Francisco", url:"./games/subway-surfers-san-francisco", category:"action"},
    {name:"Super Mario Bros", url:"./games/super-mario-bros/", category:"emulator"},
    {name:"Super Smash Bros", url:"./games/super-smash-bros/", category:"emulator"},
    {name:"Survivor.io", url:"./games/survivorio/", category:"io"},
    {name:"Swords and Souls", url:"./games/swords-and-souls/", category:"adventure"},
    {name:"Temple Run 2", url:"./games/temple-run-2/", category:"action"},
    {name:"Territorial.io", url:"./games/territorialio/", category:"io"},
    {name:"Tetris", url:"./games/tetris/", category:"puzzle"},
    {name:"The Impossible Quiz", url:"./games/the-impossible-quiz/", category:"puzzle"},
    {name:"The Legend of Zelda: Majora's Mask", url:"./games/the-legend-of-zelda-majoras-mask/", category:"emulator"},
    {name:"The Legend of Zelda: Ocarina of Time", url:"./games/the-legend-of-zelda-ocarina-of-time/", category:"emulator"},
    {name:"The Oregon Trail", url:"./games/the-oregon-trail", category:"adventure"},
    {name:"This is the Only Level", url:"./games/this-is-the-only-level/", category:"puzzle"},
    {name:"Time Shooter 2", url:"./games/time-shooter-2/", category:"action"},
    {name:"Time Shooter 3 S.W.A.T", url:"./games/time-shooter-3-swat/", category:"action"},
    {name:"Tiny Fishing", url:"./games/tiny-fishing/", category:"other"},
    {name:"Tomb of the Mask", url:"./games/tomb-of-the-mask/", category:"platformer"},
    {name:"Tunnel Rush 2", url:"./games/tunnel-rush-2/", category:"action"},
    {name:"Vex 7", url:"./games/vex-7/", category:"platformer"},
    {name:"Volley Random", url:"./games/volley-random/", category:"sports"},
    {name:"We Become What We Behold", url:"./games/we-become-what-we-behold/", category:"puzzle"},
    {name:"Wordle+", url:"./games/wordle+/", category:"puzzle"},
    {name:"World's Hardest Game 3", url:"./games/worlds-hardest-game-3/", category:"puzzle"},
    {name:"Wrestle Bros", url:"./games/wrestle-bros/", category:"sports"}
];